In [3]:
import pandas as pd
df = pd.read_csv(r'F:\GitHub projects\teams2.csv')
df

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#,Club,Pays,22/23,23/24,24/25,25/26,26/27,Points
2,1,Bayern,NaN,27.000,28.000,27.250,39.250,NaN,121.500
3,2,Arsenal,NaN,17.000,22.000,36.000,43.000,NaN,118.000
4,3,Real Madrid,NaN,29.000,34.000,24.500,27.000,NaN,114.500
5,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
6,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
7,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
8,5,Inter,NaN,29.000,20.000,40.250,19.750,NaN,109.000
9,6,Man City,NaN,33.000,28.000,14.750,22.750,NaN,98.500
10,7,Barcelone,NaN,9.000,23.000,36.250,30.000,NaN,98.250
11,8,Liverpool,NaN,19.000,20.000,29.500,28.500,NaN,97.000
12,9,Leverkusen,NaN,19.000,29.000,23.250,19.750,NaN,91.000
13,10,Dortmund,NaN,18.000,29.000,27.750,16.000,NaN,90.750
14,11,Atlético,NaN,8.000,24.000,26.500,27.250,NaN,85.750
15,12,Aston Villa,NaN,NaN,17.000,30.250,33.750,NaN,81.000
16,13,Tottenham,NaN,18.000,-,32.250,26.750,NaN,77.000
17,14,Fiorentina,NaN,20.000,22.000,20.000,14.250,NaN,76.250
18,15,AS Roma,NaN,22.000,21.000,14.500,17.250,NaN,74.750
19,16,Chelsea,NaN,21.000,-,30.000,23.250,NaN,74.250
20,16,Chelsea,NaN,21.000,-,30.000,23.250,NaN,74.250
21,17,FC Porto,NaN,18.000,19.000,9.750,24.000,NaN,70.750
22,17,FC Porto,NaN,18.000,19.000,9.750,24.000,NaN,70.750
23,18,Benfica,NaN,25.000,14.000,18.750,12.250,NaN,70.000
24,19,Club Bruges,NaN,17.000,21.000,15.750,14.500,NaN,68.250
25,20,Atalanta,NaN,-,28.000,21.000,19.000,NaN,68.000
26,21,Sporting,NaN,14.000,12.000,14.500,27.500,NaN,68.000
27,22,Real Betis,NaN,16.000,6.000,19.250,21.750,NaN,63.000
28,23,PSV,NaN,11.000,17.000,21.250,12.000,NaN,61.250
29,23,PSV,NaN,11.000,17.000,21.250,12.000,NaN,61.250
30,24,AC Milan,NaN,24.000,16.000,19.000,-,NaN,59.000
31,25,Manchester Utd.,NaN,19.000,7.000,32.500,-,NaN,58.500

In [5]:
#rename columns
df.rename(columns={
    'Column2': 'Club',
    'Column3': 'Country',
    'Column4': '22/23',
    'Column5': '23/24',
    'Column6': '24/25',
    'Column7': '25/26',
    'Column8': '26/27',
    'Column9': 'Points'
}, inplace=True)

In [8]:
df

,Column1,Club,Country,22/23,23/24,24/25,25/26,26/27,Points
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#,Club,Pays,22/23,23/24,24/25,25/26,26/27,Points
2,1,Bayern,NaN,27.000,28.000,27.250,39.250,NaN,121.500
3,2,Arsenal,NaN,17.000,22.000,36.000,43.000,NaN,118.000
4,3,Real Madrid,NaN,29.000,34.000,24.500,27.000,NaN,114.500
5,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
6,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
7,4,PSG,NaN,19.000,23.000,33.500,36.500,NaN,112.000
8,5,Inter,NaN,29.000,20.000,40.250,19.750,NaN,109.000
9,6,Man City,NaN,33.000,28.000,14.750,22.750,NaN,98.500
10,7,Barcelone,NaN,9.000,23.000,36.250,30.000,NaN,98.250
11,8,Liverpool,NaN,19.000,20.000,29.500,28.500,NaN,97.000
12,9,Leverkusen,NaN,19.000,29.000,23.250,19.750,NaN,91.000
13,10,Dortmund,NaN,18.000,29.000,27.750,16.000,NaN,90.750
14,11,Atlético,NaN,8.000,24.000,26.500,27.250,NaN,85.750
15,12,Aston Villa,NaN,NaN,17.000,30.250,33.750,NaN,81.000
16,13,Tottenham,NaN,18.000,-,32.250,26.750,NaN,77.000
17,14,Fiorentina,NaN,20.000,22.000,20.000,14.250,NaN,76.250
18,15,AS Roma,NaN,22.000,21.000,14.500,17.250,NaN,74.750
19,16,Chelsea,NaN,21.000,-,30.000,23.250,NaN,74.250
20,16,Chelsea,NaN,21.000,-,30.000,23.250,NaN,74.250
21,17,FC Porto,NaN,18.000,19.000,9.750,24.000,NaN,70.750
22,17,FC Porto,NaN,18.000,19.000,9.750,24.000,NaN,70.750
23,18,Benfica,NaN,25.000,14.000,18.750,12.250,NaN,70.000
24,19,Club Bruges,NaN,17.000,21.000,15.750,14.500,NaN,68.250
25,20,Atalanta,NaN,-,28.000,21.000,19.000,NaN,68.000
26,21,Sporting,NaN,14.000,12.000,14.500,27.500,NaN,68.000
27,22,Real Betis,NaN,16.000,6.000,19.250,21.750,NaN,63.000
28,23,PSV,NaN,11.000,17.000,21.250,12.000,NaN,61.250
29,23,PSV,NaN,11.000,17.000,21.250,12.000,NaN,61.250
30,24,AC Milan,NaN,24.000,16.000,19.000,-,NaN,59.000
31,25,Manchester Utd.,NaN,19.000,7.000,32.500,-,NaN,58.500

In [ ]:
df.drop('Column1' , axis=1 , inplace= True)
#ditching column (column is axis = 1)

In [ ]:
df.drop(0)
#ditch rows another form is df.drop(index= [0])

               Club Country   22/23   23/24   24/25   25/26  26/27   Points
1              Club    Pays   22/23   23/24   24/25   25/26  26/27   Points
2            Bayern     NaN  27.000  28.000  27.250  39.250    NaN  121.500
3           Arsenal     NaN  17.000  22.000  36.000  43.000    NaN  118.000
4       Real Madrid     NaN  29.000  34.000  24.500  27.000    NaN  114.500
5               PSG     NaN  19.000  23.000  33.500  36.500    NaN  112.000
6               PSG     NaN  19.000  23.000  33.500  36.500    NaN  112.000
7               PSG     NaN  19.000  23.000  33.500  36.500    NaN  112.000
8             Inter     NaN  29.000  20.000  40.250  19.750    NaN  109.000
9          Man City     NaN  33.000  28.000  14.750  22.750    NaN   98.500
10        Barcelone     NaN   9.000  23.000  36.250  30.000    NaN   98.250
11        Liverpool     NaN  19.000  20.000  29.500  28.500    NaN   97.000
12       Leverkusen     NaN  19.000  29.000  23.250  19.750    NaN   91.000
13         Dortmund     NaN  18.000  29.000  27.750  16.000    NaN   90.750
14         Atlético     NaN   8.000  24.000  26.500  27.250    NaN   85.750
15      Aston Villa     NaN     NaN  17.000  30.250  33.750    NaN   81.000
16        Tottenham     NaN  18.000       -  32.250  26.750    NaN   77.000
17       Fiorentina     NaN  20.000  22.000  20.000  14.250    NaN   76.250
18          AS Roma     NaN  22.000  21.000  14.500  17.250    NaN   74.750
19          Chelsea     NaN  21.000       -  30.000  23.250    NaN   74.250
20          Chelsea     NaN  21.000       -  30.000  23.250    NaN   74.250
21         FC Porto     NaN  18.000  19.000   9.750  24.000    NaN   70.750
22         FC Porto     NaN  18.000  19.000   9.750  24.000    NaN   70.750
23          Benfica     NaN  25.000  14.000  18.750  12.250    NaN   70.000
24      Club Bruges     NaN  17.000  21.000  15.750  14.500    NaN   68.250
25         Atalanta     NaN       -  28.000  21.000  19.000    NaN   68.000
26         Sporting     NaN  14.000  12.000  14.500  27.500    NaN   68.000
27       Real Betis     NaN  16.000   6.000  19.250  21.750    NaN   63.000
28              PSV     NaN  11.000  17.000  21.250  12.000    NaN   61.250
29              PSV     NaN  11.000  17.000  21.250  12.000    NaN   61.250
30         AC Milan     NaN  24.000  16.000  19.000       -    NaN   59.000
31  Manchester Utd.     NaN  19.000   7.000  32.500       -    NaN   58.500

In [ ]:
df.drop([0,1],inplace= True)

KeyError: '[0, 1] not found in axis'

In [19]:
df = df.reset_index(drop=True)

In [20]:
df.head()

          Club Country   22/23   23/24   24/25   25/26 26/27   Points
0       Bayern     NaN  27.000  28.000  27.250  39.250   NaN  121.500
1      Arsenal     NaN  17.000  22.000  36.000  43.000   NaN  118.000
2  Real Madrid     NaN  29.000  34.000  24.500  27.000   NaN  114.500
3          PSG     NaN  19.000  23.000  33.500  36.500   NaN  112.000
4          PSG     NaN  19.000  23.000  33.500  36.500   NaN  112.000

In [23]:
df = df.drop(columns=['Country', '26/27'])

In [24]:
df.duplicated()

0     False
1     False
2     False
3     False
4      True
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29    False
dtype: bool

In [ ]:
df[df['Club'].duplicated()==1]
#gets all duplicates

        Club   22/23   23/24   24/25   25/26   Points
4        PSG  19.000  23.000  33.500  36.500  112.000
5        PSG  19.000  23.000  33.500  36.500  112.000
18   Chelsea  21.000       -  30.000  23.250   74.250
20  FC Porto  18.000  19.000   9.750  24.000   70.750
27       PSV  11.000  17.000  21.250  12.000   61.250

In [26]:
df.drop([4,5,18,29,27],inplace= True)

In [27]:
df

           Club   22/23   23/24   24/25   25/26   Points
0        Bayern  27.000  28.000  27.250  39.250  121.500
1       Arsenal  17.000  22.000  36.000  43.000  118.000
2   Real Madrid  29.000  34.000  24.500  27.000  114.500
3           PSG  19.000  23.000  33.500  36.500  112.000
6         Inter  29.000  20.000  40.250  19.750  109.000
7      Man City  33.000  28.000  14.750  22.750   98.500
8     Barcelone   9.000  23.000  36.250  30.000   98.250
9     Liverpool  19.000  20.000  29.500  28.500   97.000
10   Leverkusen  19.000  29.000  23.250  19.750   91.000
11     Dortmund  18.000  29.000  27.750  16.000   90.750
12     Atlético   8.000  24.000  26.500  27.250   85.750
13  Aston Villa     NaN  17.000  30.250  33.750   81.000
14    Tottenham  18.000       -  32.250  26.750   77.000
15   Fiorentina  20.000  22.000  20.000  14.250   76.250
16      AS Roma  22.000  21.000  14.500  17.250   74.750
17      Chelsea  21.000       -  30.000  23.250   74.250
19     FC Porto  18.000  19.000   9.750  24.000   70.750
20     FC Porto  18.000  19.000   9.750  24.000   70.750
21      Benfica  25.000  14.000  18.750  12.250   70.000
22  Club Bruges  17.000  21.000  15.750  14.500   68.250
23     Atalanta       -  28.000  21.000  19.000   68.000
24     Sporting  14.000  12.000  14.500  27.500   68.000
25   Real Betis  16.000   6.000  19.250  21.750   63.000
26          PSV  11.000  17.000  21.250  12.000   61.250
28     AC Milan  24.000  16.000  19.000       -   59.000

In [28]:
df = df.reset_index(drop= True)
df

           Club   22/23   23/24   24/25   25/26   Points
0        Bayern  27.000  28.000  27.250  39.250  121.500
1       Arsenal  17.000  22.000  36.000  43.000  118.000
2   Real Madrid  29.000  34.000  24.500  27.000  114.500
3           PSG  19.000  23.000  33.500  36.500  112.000
4         Inter  29.000  20.000  40.250  19.750  109.000
5      Man City  33.000  28.000  14.750  22.750   98.500
6     Barcelone   9.000  23.000  36.250  30.000   98.250
7     Liverpool  19.000  20.000  29.500  28.500   97.000
8    Leverkusen  19.000  29.000  23.250  19.750   91.000
9      Dortmund  18.000  29.000  27.750  16.000   90.750
10     Atlético   8.000  24.000  26.500  27.250   85.750
11  Aston Villa     NaN  17.000  30.250  33.750   81.000
12    Tottenham  18.000       -  32.250  26.750   77.000
13   Fiorentina  20.000  22.000  20.000  14.250   76.250
14      AS Roma  22.000  21.000  14.500  17.250   74.750
15      Chelsea  21.000       -  30.000  23.250   74.250
16     FC Porto  18.000  19.000   9.750  24.000   70.750
17     FC Porto  18.000  19.000   9.750  24.000   70.750
18      Benfica  25.000  14.000  18.750  12.250   70.000
19  Club Bruges  17.000  21.000  15.750  14.500   68.250
20     Atalanta       -  28.000  21.000  19.000   68.000
21     Sporting  14.000  12.000  14.500  27.500   68.000
22   Real Betis  16.000   6.000  19.250  21.750   63.000
23          PSV  11.000  17.000  21.250  12.000   61.250
24     AC Milan  24.000  16.000  19.000       -   59.000

In [34]:
df.dtypes

Club      str
22/23     str
23/24     str
24/25     str
25/26     str
Points    str
dtype: object

In [39]:
for col in ['22/23','23/24','24/25','25/26']:
    print(col, df[col].str.strip().unique())

22/23 <StringArray>
['27.000', '17.000', '29.000', '19.000', '33.000',  '9.000', '18.000',
  '8.000',      nan, '20.000', '22.000', '21.000', '25.000',      '-',
 '14.000', '16.000', '11.000', '24.000']
Length: 18, dtype: str
23/24 <StringArray>
['28.000', '22.000', '34.000', '23.000', '20.000', '29.000', '24.000',
 '17.000',      '-', '21.000', '19.000', '14.000', '12.000',  '6.000',
 '16.000']
Length: 15, dtype: str
24/25 <StringArray>
['27.250', '36.000', '24.500', '33.500', '40.250', '14.750', '36.250',
 '29.500', '23.250', '27.750', '26.500', '30.250', '32.250', '20.000',
 '14.500', '30.000',  '9.750', '18.750', '15.750', '21.000', '19.250',
 '21.250', '19.000']
Length: 23, dtype: str
25/26 <StringArray>
['39.250', '43.000', '27.000', '36.500', '19.750', '22.750', '30.000',
 '28.500', '16.000', '27.250', '33.750', '26.750', '14.250', '17.250',
 '23.250', '24.000', '12.250', '14.500', '19.000', '27.500', '21.750',
 '12.000',      '-']
Length: 23, dtype: str

In [40]:
df[['22/23','23/24','24/25','25/26']] = df[['22/23','23/24','24/25','25/26']].replace('-', pd.NA)

In [41]:
df

           Club   22/23   23/24   24/25   25/26   Points
0        Bayern  27.000  28.000  27.250  39.250  121.500
1       Arsenal  17.000  22.000  36.000  43.000  118.000
2   Real Madrid  29.000  34.000  24.500  27.000  114.500
3           PSG  19.000  23.000  33.500  36.500  112.000
4         Inter  29.000  20.000  40.250  19.750  109.000
5      Man City  33.000  28.000  14.750  22.750   98.500
6     Barcelone   9.000  23.000  36.250  30.000   98.250
7     Liverpool  19.000  20.000  29.500  28.500   97.000
8    Leverkusen  19.000  29.000  23.250  19.750   91.000
9      Dortmund  18.000  29.000  27.750  16.000   90.750
10     Atlético   8.000  24.000  26.500  27.250   85.750
11  Aston Villa     NaN  17.000  30.250  33.750   81.000
12    Tottenham  18.000     NaN  32.250  26.750   77.000
13   Fiorentina  20.000  22.000  20.000  14.250   76.250
14      AS Roma  22.000  21.000  14.500  17.250   74.750
15      Chelsea  21.000     NaN  30.000  23.250   74.250
16     FC Porto  18.000  19.000   9.750  24.000   70.750
17     FC Porto  18.000  19.000   9.750  24.000   70.750
18      Benfica  25.000  14.000  18.750  12.250   70.000
19  Club Bruges  17.000  21.000  15.750  14.500   68.250
20     Atalanta     NaN  28.000  21.000  19.000   68.000
21     Sporting  14.000  12.000  14.500  27.500   68.000
22   Real Betis  16.000   6.000  19.250  21.750   63.000
23          PSV  11.000  17.000  21.250  12.000   61.250
24     AC Milan  24.000  16.000  19.000     NaN   59.000

In [43]:
df[['22/23','23/24','24/25','25/26']] = df[['22/23','23/24','24/25','25/26']].astype('float')

In [44]:
df[['22/23','23/24','24/25','25/26']] = df[['22/23','23/24','24/25','25/26']].fillna('0')

In [47]:
df[['22/23','23/24','24/25','25/26']] = df[['22/23','23/24','24/25','25/26']].astype(float)

In [51]:
df['avg_score']= df[['22/23','23/24','24/25','25/26']].mean(axis= 1)
df

           Club  22/23  23/24  24/25  25/26   Points  avg_score
0        Bayern   27.0   28.0  27.25  39.25  121.500    30.3750
1       Arsenal   17.0   22.0  36.00  43.00  118.000    29.5000
2   Real Madrid   29.0   34.0  24.50  27.00  114.500    28.6250
3           PSG   19.0   23.0  33.50  36.50  112.000    28.0000
4         Inter   29.0   20.0  40.25  19.75  109.000    27.2500
5      Man City   33.0   28.0  14.75  22.75   98.500    24.6250
6     Barcelone    9.0   23.0  36.25  30.00   98.250    24.5625
7     Liverpool   19.0   20.0  29.50  28.50   97.000    24.2500
8    Leverkusen   19.0   29.0  23.25  19.75   91.000    22.7500
9      Dortmund   18.0   29.0  27.75  16.00   90.750    22.6875
10     Atlético    8.0   24.0  26.50  27.25   85.750    21.4375
11  Aston Villa    0.0   17.0  30.25  33.75   81.000    20.2500
12    Tottenham   18.0    0.0  32.25  26.75   77.000    19.2500
13   Fiorentina   20.0   22.0  20.00  14.25   76.250    19.0625
14      AS Roma   22.0   21.0  14.50  17.25   74.750    18.6875
15      Chelsea   21.0    0.0  30.00  23.25   74.250    18.5625
16     FC Porto   18.0   19.0   9.75  24.00   70.750    17.6875
17     FC Porto   18.0   19.0   9.75  24.00   70.750    17.6875
18      Benfica   25.0   14.0  18.75  12.25   70.000    17.5000
19  Club Bruges   17.0   21.0  15.75  14.50   68.250    17.0625
20     Atalanta    0.0   28.0  21.00  19.00   68.000    17.0000
21     Sporting   14.0   12.0  14.50  27.50   68.000    17.0000
22   Real Betis   16.0    6.0  19.25  21.75   63.000    15.7500
23          PSV   11.0   17.0  21.25  12.00   61.250    15.3125
24     AC Milan   24.0   16.0  19.00   0.00   59.000    14.7500

In [52]:
df['check_sum']= df[['22/23','23/24','24/25','25/26']].sum(axis=1)
df[['Club','Points','check_sum']]

           Club   Points  check_sum
0        Bayern  121.500     121.50
1       Arsenal  118.000     118.00
2   Real Madrid  114.500     114.50
3           PSG  112.000     112.00
4         Inter  109.000     109.00
5      Man City   98.500      98.50
6     Barcelone   98.250      98.25
7     Liverpool   97.000      97.00
8    Leverkusen   91.000      91.00
9      Dortmund   90.750      90.75
10     Atlético   85.750      85.75
11  Aston Villa   81.000      81.00
12    Tottenham   77.000      77.00
13   Fiorentina   76.250      76.25
14      AS Roma   74.750      74.75
15      Chelsea   74.250      74.25
16     FC Porto   70.750      70.75
17     FC Porto   70.750      70.75
18      Benfica   70.000      70.00
19  Club Bruges   68.250      68.25
20     Atalanta   68.000      68.00
21     Sporting   68.000      68.00
22   Real Betis   63.000      63.00
23          PSV   61.250      61.25
24     AC Milan   59.000      59.00

In [53]:
df = df.drop(columns=['check_sum'])
df

           Club  22/23  23/24  24/25  25/26   Points  avg_score
0        Bayern   27.0   28.0  27.25  39.25  121.500    30.3750
1       Arsenal   17.0   22.0  36.00  43.00  118.000    29.5000
2   Real Madrid   29.0   34.0  24.50  27.00  114.500    28.6250
3           PSG   19.0   23.0  33.50  36.50  112.000    28.0000
4         Inter   29.0   20.0  40.25  19.75  109.000    27.2500
5      Man City   33.0   28.0  14.75  22.75   98.500    24.6250
6     Barcelone    9.0   23.0  36.25  30.00   98.250    24.5625
7     Liverpool   19.0   20.0  29.50  28.50   97.000    24.2500
8    Leverkusen   19.0   29.0  23.25  19.75   91.000    22.7500
9      Dortmund   18.0   29.0  27.75  16.00   90.750    22.6875
10     Atlético    8.0   24.0  26.50  27.25   85.750    21.4375
11  Aston Villa    0.0   17.0  30.25  33.75   81.000    20.2500
12    Tottenham   18.0    0.0  32.25  26.75   77.000    19.2500
13   Fiorentina   20.0   22.0  20.00  14.25   76.250    19.0625
14      AS Roma   22.0   21.0  14.50  17.25   74.750    18.6875
15      Chelsea   21.0    0.0  30.00  23.25   74.250    18.5625
16     FC Porto   18.0   19.0   9.75  24.00   70.750    17.6875
17     FC Porto   18.0   19.0   9.75  24.00   70.750    17.6875
18      Benfica   25.0   14.0  18.75  12.25   70.000    17.5000
19  Club Bruges   17.0   21.0  15.75  14.50   68.250    17.0625
20     Atalanta    0.0   28.0  21.00  19.00   68.000    17.0000
21     Sporting   14.0   12.0  14.50  27.50   68.000    17.0000
22   Real Betis   16.0    6.0  19.25  21.75   63.000    15.7500
23          PSV   11.0   17.0  21.25  12.00   61.250    15.3125
24     AC Milan   24.0   16.0  19.00   0.00   59.000    14.7500